---
# tasks file for mysql_db
    - name: Install MySQL community repository
      yum:
        name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
        state: present

    - name: Install MySQL database
      vars:
       mysql_packages: [mysql-server,mysql-devel]
      yum:
        name: "{{ mysql_packages }}"
        state: present
        # Removing with_items as now deprecated

    - name: Install mysql-python package
      yum:
        name: MySQL-python
        state: present

    - name: create MySQL configuration file
      copy:
        content: |
          [client]
          user=root
          password="@targ8et"
        dest: "/etc/.my.cnf"

    - name: Start MySQL Service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create Database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
